version: "3.7"

services:
  db:
    build:
      context: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always

  bff:
    build:
      context: ./bff
    depends_on:
      - db
      - api
      - reverse-proxy
    environment:
      NODE_ENV: development
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: dbtest
      PGPORT: 5432
      PORT: 3000
      API_URL: http://api:3333
    ports:
      - 3000:3000

  api:
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: job_platform
      PGPORT: 5432
      PORT: 3333
    build:
      context: ./api

  reverse-proxy:
    depends_on:
      - ui
      - adminer
    build:
      context: ./reverse-proxy
    ports:
      - 80:80
  ui:
    environment:
      NODE_ENV: development
    build:
      context: ./ui

volumes:
  pgdata:
